train: ../train/images
val: ../valid/images
test: ../test/images

nc: 4
names: ['nike fake air force', 'nike fake jordan 1', 'nike original air force', 'nike original jordan 1']

roboflow:
  workspace: default-kupxs
  project: counterfeit-nike-shoes-detection
  version: 2
  license: CC BY 4.0
  url: https://universe.roboflow.com/default-kupxs/counterfeit-nike-shoes-detection/dataset/2